language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make test
after_success:
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  app: tranquil-sands-44590
  api_key: ${HEROKU_API_KEY}
make test_xunit
